[build]
  # Directory to change to before starting a build
  base = "."
  
  # Directory that contains the deploy-ready HTML files and assets
  publish = "dist"
  
  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

[[redirects]]
  # Handle client-side routing for SPA
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover
  for = "/*"
  
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000"

[[headers]]
  # Special caching for HTML files
  for = "/*.html"
  
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  # Cache images for 1 month
  for = "/assets/*"
  
  [headers.values]
    Cache-Control = "public, max-age=2592000"